fioprotocol/fio.contracts

- contracts/fio.common/fioerror.hpp
- contracts/fio.system/include/fio.system/native.hpp
This pr adds addiction and reaction into the system contract ABI.
> add addaction and remaction and one constant

- contracts/fio.address/fio.address.abi
> Revert fio.address.abi to reflect 32-bit expiration in domains table

- contracts/fio.address/fio.address.abi
Reverts fioprotocol/fio.contracts#26
> Revert "Revert fio.address.abi to reflect 32-bit expiration in domains table"

- contracts/fio.address/fio.address.cpp
Future PR will optimize this further.
> Decrease address limit from 1000 to 200

- contracts/fio.address/fio.address.cpp
- contracts/fio.address/fio.address.hpp
- contracts/fio.common/fio.accounts.hpp
Reverts fioprotocol/fio.contracts#40 for later release.
> Revert "Optimize addaddress with new searching algorithm "

- contracts/fio.address/fio.address.cpp
Reverts fioprotocol/fio.contracts#39
> Revert "Decrease address limit from 1000 to 200"

- contracts/fio.address/fio.address.cpp
- contracts/fio.common/fio.common.hpp
- contracts/fio.fee/fio.fee.cpp
- contracts/fio.request.obt/fio.request.obt.cpp
- contracts/fio.system/src/voting.cpp
- contracts/fio.token/src/fio.token.cpp
Contract change:
**** MULTI-CONTRACT UPDATE! Shared header ****
https://github.com/fioprotocol/fio.contracts/commit/99f2479d98a68962bf254838c35f6cb8396ccd43 - Add support for endpoints in transfer memos, pdate fee endpoints in asserts, fio_fees, index search to use shared references
> MAS-1897 - Add transaction information to memo field for fio_fees

- contracts/fio.common/fio.common.hpp
- contracts/fio.fee/fio.fee.cpp
https://fioprotocol.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=BD&modal=detail&selectedIssue=BD-2145
> update fee endpoint logic for setfeevote, bundlevote, setfeemulti

- contracts/fio.address/fio.address.cpp
- contracts/fio.address/fio.address.hpp
- contracts/fio.common/fio.accounts.hpp
Reverts fioprotocol/fio.contracts#41 which was merged earlier in error.
> Optimize addaddress with new searching algorithm

- contracts/fio.system/src/voting.cpp
fixes #29 
Please double check...
> bug fix of issue 29 when regproxy with an existing voters record

- contracts/fio.token/src/fio.token.cpp
Left over from development testing
> Turn off debug mode in fio.token

- contracts/fio.address/fio.address.cpp
- contracts/fio.common/fio.common.hpp
- contracts/fio.common/fioerror.hpp
- contracts/fio.system/include/fio.system/fio.system.hpp
- contracts/fio.system/src/fio.system.cpp
- contracts/fio.system/src/voting.cpp
- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.token/src/fio.token.cpp
this will be filled in as the project continues
> FIP-6 FIP-21 changes for general locks and staking

- contracts/fio.request.obt/fio.request.obt.abi
- contracts/fio.request.obt/fio.request.obt.cpp
- contracts/fio.request.obt/fio.request.obt.hpp
ABI and contract changes, optimizations, and bug fixes that were found during testing.
> Fip-1b testing fixes

- contracts/fio.address/fio.address.cpp
- contracts/fio.system/src/fio.system.cpp
- contracts/fio.system/src/voting.cpp
- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.token/src/fio.token.cpp
this PR fixes the issue that an account holding genesis granted locked tokens
cannot call register domain.
this PR also removes debug print statements in the hopes of keeping contract size a bit smaller.
> Bravo release target -- FIP-6 code cleanup, fix for BD-2244

- contracts/fio.request.obt/fio.request.obt.cpp
> Change id to use proper primary key setting

- contracts/fio.address/fio.address.cpp
- contracts/fio.token/src/fio.token.cpp
fix bug, payee account is being auto proxied instead of the signing account
> auto proxy issue

- contracts/fio.request.obt/fio.request.obt.cpp
Unneeded code that was causing CPU exceed errors on devnet
> Update id fix for migration process

- contracts/fio.treasury/fio.treasury.cpp
increase BP rewards as per FIP-23
change BPMAXRESERVE to become 20M
> BD-2353, FIP-23 increase BP reserves.

- contracts/fio.request.obt/fio.request.obt.abi
- contracts/fio.request.obt/fio.request.obt.cpp
- contracts/fio.request.obt/fio.request.obt.hpp
The following PR will be the final step in the migration process. This includes the removal of old migration temp actions, removal of previously used index tables, and restructures the API endpoints to allow for improved results.
> [FIP-1.b] Contracts Part 3: Final Integration of request and obt data restructuring. (#183)(OLD #10)

- contracts/fio.request.obt/fio.request.obt.abi
- contracts/fio.request.obt/fio.request.obt.cpp
- contracts/fio.request.obt/fio.request.obt.hpp
Reverts fioprotocol/fio.contracts#114
> Revert "[FIP-1.b] Contracts Part 3: Final Integration of request and obt data restructuring. (#183)(OLD #10)"

- contracts/fio.system/include/fio.system/fio.system.hpp
- contracts/fio.system/src/voting.cpp
get rid of unused calls, clean up commented code.
>  FIP-21 code cleanup for staking

- contracts/fio.staking/fio.staking.cpp
small code cleanup on staking contract
> FIP-21  code cleanup staking contract

- contracts/fio.staking/fio.staking.cpp
correct the calculations used for staking rewards
NOTE -- this PR introduces alot of debug code, which should be enabled for QA and UAT, but MUST be removed before any release build is created..
> FIP-21 changes to correct the math in the staking rewards

- contracts/fio.staking/fio.staking.cpp
this PR fixes the bug when the unlock general locking period being added is at the end of the existing periods..
> FIP-21 staking Fix bug when unstaking and new lock period is at the end of the periods

- contracts/fio.staking/fio.staking.cpp
fix logic error in setting of insert index
> FIP-21 fix logic error in setting of insert index on general lock adaption

- contracts/fio.staking/fio.staking.cpp
> FIP-21 Staking fix computation of roe

- contracts/fio.staking/fio.staking.cpp
> FIP-21 Staking rename variables

- contracts/fio.staking/fio.staking.cpp
get rid of rounding on srpstoclaim calc.
> FIP-21 Staking get rid of rounding on srpstoclaim calc

- contracts/fio.staking/fio.staking.cpp
force truncation of double values instead of implied type conversion.
> FIP-21 Staking -- force truncation of the computed ROE and other values

- contracts/fio.staking/fio.staking.cpp
update prints to show the value of comined token pool during stake tx
> FIP-21 Staking  update prints to show the value of combined token pool during stake tx

- contracts/fio.address/fio.address.abi
- contracts/fio.address/fio.address.cpp
- contracts/fio.common/fioerror.hpp
- contracts/fio.request.obt/fio.request.obt.cpp
- contracts/fio.system/src/voting.cpp
- contracts/fio.treasury/fio.treasury.cpp
https://github.com/fioprotocol/fips/blob/master/fip-0031.md
> FIP-31: Eliminate FIO Address Expiration

- contracts/fio.staking/fio.staking.cpp
update staking contract to fix errant error details
> FIP 21 -- Staking -- BD-3016 update errant error details

- contracts/fio.staking/fio.staking.cpp
update staking contract to fix errant error details
> update errant error details (into develop branch)

- contracts/fio.address/fio.address.cpp
Allow for transfer of domain that has been expired (FIP-17b)
https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/28?modal=detail&selectedIssue=BD-2998
> Xferdomain update

- contracts/fio.common/fio.common.hpp
- contracts/fio.request.obt/fio.request.obt.cpp
https://fioprotocol.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=BD&modal=detail&selectedIssue=BD-2150
> newfundsreq/recordobt increase max content 

- contracts/fio.address/fio.address.cpp
- contracts/fio.common/fio.common.hpp
https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/28?modal=detail&selectedIssue=BD-2912
> Bump up ram per NFT added 

- contracts/fio.address/fio.address.cpp
Spec change:
https://github.com/fioprotocol/fips/blob/master/fip-0035.md
https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/2?modal=detail&selectedIssue=BD-3100
> change token_id supported length to 128

- contracts/fio.common/fio.common.hpp
- contracts/fio.request.obt/fio.request.obt.cpp
https://github.com/fioprotocol/fips/blob/master/fip-0032.md
https://github.com/fioprotocol/fips/blob/master/fip-0034.md
> FIP-32 / FIP-34 ( Increased content on newfundsreq and recordobt )

- contracts/fio.staking/fio.staking.cpp
set the rewards activation date and time for main net launch
> FIP-21 Staking -- set main net rewards start date/time

- contracts/fio.system/src/voting.cpp
- contracts/fio.treasury/fio.treasury.cpp
Includes:
BD-2143
BD-2737
BD-3017
> BD-3073 Bug Stomp ( Part 1 ) 

- contracts/fio.common/fio.common.hpp
- contracts/fio.escrow/fio.escrow.cpp
increased amount of bytes the ram will be increased by
removed ram bump on actions when it's not needed.
> Escrow ram adjust

- contracts/fio.token/src/fio.token.cpp
fix bug in addgenlocked, make canvote proper type
> FIP-41, fix bug in general locks, addgenlocked does not set can_vote properly

- contracts/fio.token/src/fio.token.cpp
fix bug regression tests failing
> FIP-41 fix bug found by general lock regression tests

- contracts/fio.address/fio.address.abi
[BD-3237](https://fioprotocol.atlassian.net/browse/BD-3237)
> Remove modexpire from fio.address abi

- contracts/fio.staking/fio.staking.cpp
- contracts/fio.token/src/fio.token.cpp
move the tpid processing so its always completed regardless of bundle count.
NOTE--- 
This PR needs tested as indicated in this story before it can be considered for release to test net.
https://fioprotocol.atlassian.net/browse/BD-3552
> BD-3552  always do the tpid processing in Stake FIO action

- contracts/fio.treasury/fio.treasury.cpp
add staking contract auth checks into fdtnrwdupdat
> BD-3552 -- add the staking contract into the auth checks for fdtnrwdupdat

- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.token/src/fio.token.cpp
change logic and error messages for can_vote to meet revised spec.
> FIP-41 Revised error messaging -- change error logic and messages for can_vote

- contracts/fio.system/src/voting.cpp
modify logic to clear existing proxy in regiproxy BD-2269
NOTE -- complete tpid,  proxy, and new test cases for the bug must be completed for these changes
> BD-2269 modify logic to clear proxy in regiproxy

- contracts/fio.address/fio.address.cpp
https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/2?modal=detail&selectedIssue=BD-3826
Fix is in 2 parts-
-Correction to addnft action - token_id_hash is main lookup key and not being configured in any instance where the token_id field is empty. This has been corrected.
-remnft action has been corrected to remove nft sigs that have the invalid property when token_id field was empty
Related PR https://github.com/fioprotocol/fio.contracts/pull/256
> Bugfix bd3826

- contracts/fio.oracle/fio.oracle.cpp
> [BD-3874] Fix when not all oracles have set fees

- contracts/fio.staking/fio.staking.cpp
fix BD-3941
handle edge case when we unstable and have only expired periods in the existing locks.
> BD-3941. -- address this bug

- contracts/fio.staking/fio.staking.cpp
> BD-3941 fix > develop

- README.md
README update to include missing contracts
> BD-3946: Updated README to include missing contracts

- contracts/fio.address/fio.address.abi
- contracts/fio.address/fio.address.cpp
- contracts/fio.address/fio.address.hpp
- contracts/fio.common/fio.common.hpp
- contracts/fio.system/include/fio.system/fio.system.hpp
- contracts/fio.system/include/fio.system/native.hpp
- contracts/fio.system/src/fio.system.cpp
- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.treasury/fio.treasury.cpp
> FIPs36-40 PR cleanup

- contracts/fio.address/fio.address.abi
- contracts/fio.address/fio.address.cpp
- contracts/fio.address/fio.address.hpp
- contracts/fio.common/fio.common.hpp
- contracts/fio.system/include/fio.system/fio.system.hpp
- contracts/fio.system/include/fio.system/native.hpp
- contracts/fio.system/src/fio.system.cpp
- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.treasury/fio.treasury.cpp
Reverts fioprotocol/fio.contracts#288
> Revert "FIPs36-40 PR cleanup"

- contracts/fio.address/fio.address.cpp
- contracts/fio.system/src/fio.system.cpp
BD-4471 make pub key error message to be Invalid FIO Public Key
more to come.
> FIP-38 bug fix iteration 02082023

- contracts/fio.address/fio.address.cpp
BD-4484 ram payer is always actor
> BD-4484 ram payer is always actor

- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.token/src/fio.token.cpp
https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/2?modal=detail&selectedIssue=BD-2893
> unpack and dont allow actor to run contract on their account

- contracts/fio.token/include/fio.token/fio.token.hpp
- contracts/fio.token/src/fio.token.cpp
Reverts fioprotocol/fio.contracts#296[
](https://fioprotocol.atlassian.net/jira/software/c/projects/BD/boards/2?modal=detail&selectedIssue=BD-2893)
> Revert "unpack and dont allow actor to run contract on their account"

- contracts/fio.address/fio.address.cpp
- contracts/fio.request.obt/fio.request.obt.cpp
BD-3746 fix auto proxy for all actions
> BD-3746 fix auto proxy for all actions

- README.md
- contracts/fio.address/fio.address.cpp
- contracts/fio.request.obt/fio.request.obt.cpp
> merge develop into dev branch

- contracts/fio.token/include/fio.token/fio.token.hpp
BD-4577 improved unlocking code logic for general locks
> BD-4577 improved general locks implementation

- contracts/fio.system/src/voting.cpp
> BD-2317 Update vote weight after un-registering

- contracts/fio.system/src/voting.cpp
BD-2280 update total vote wieght when user performs voteproxy after voting.
> BD-2280 update total vote weight when user performs voteproxy after voting

- contracts/fio.system/src/voting.cpp
> BD-4597 voting bug fix

- contracts/fio.system/src/voting.cpp
set active on update of BP info
> set active on update of  BPinfo

- CMakeLists.txt
Updated version in build file, appears to only be used during building as output logging.
> Updated version

- build.sh
- utils.sh
…build, corrected os version check msg
> BD-4617: Ubuntu 20 and 22 Upgrade updates

- docs/releases.md
Updated releases.md abi/wasm for release 2.10.x
> BD-4642 Updated releases.md abi/wasm for release 2.10
