contracts/fio.address/fio.address.cpp

Made to meet spec according to FIP
Error condition | Trigger | Type | fields:name | fields:value | Error message
-- | -- | -- | -- | -- | --
Invalid FIO address | Invalid format, or fio_address not found | 400 | "fio_address" | Value sent in, e.g. "purse@alice" | "Invalid FIO Address"

MAS-1955 - update invalid fio address error to meet spec

---

CMakeLists.txt
README.md

Now that changes have been merged after the 2.1.0 release, a new version needs to be cut to signify changes between versions.

Update develop to 2.1.1 (temp placeholder)

---

contracts/fio.treasury/fio.treasury.abi

Updated the abi for fio.treasury contract to reflect members currently in the treasurystate struct.
clio get table fio.treasury fio.treasury clockstate now returns foundation and bounty reserve tokens minted.

update fio.treasury.abi to reflect treasurystate struct (BD-1934)

---

contracts/fio.fee/fio.fee.abi
contracts/fio.fee/fio.fee.cpp

this pr changes the action name in the fee contract from update fees to compute fees, this matches the FIP-10 specification.

change name of action to computefees

---

contracts/fio.request.obt/fio.request.obt.cpp

This bug fix will require a change to the API specification. 
{
"type": "invalid_input",
"message": "An invalid request was sent in, please check the nested errors for details.",
"fields": [
{
"name": "fio_request_id",
"value": "10000000000",
"error": "Only pending requests can be rejected."
}
]
}
Issue Link: https://fioprotocol.atlassian.net/browse/BD-2157

BUG: Confirm rejected transactions have pending status

---

contracts/fio.address/fio.address.cpp
contracts/fio.common/fio_common_validator.hpp

Modifies remaddress and addaddress to allow for the "*" parameter when assigning chain level public addresses.

FIP-18: Chain-level public address

---

contracts/fio.request.obt/fio.request.obt.abi

Seems like one of the references were left. This PR deletes the ref inside the ABI file.

Update fio.request.obt.abi to remove reqledger

---

contracts/fio.common/fio.common.hpp
contracts/fio.request.obt/fio.request.obt.abi
contracts/fio.request.obt/fio.request.obt.hpp

- Increase RAM for recordobt and newfundsreq calls from `2048` -> `2560`.
- Add static casting to `fio_data_type`
- Change type from uint64_t to name for payee and payer accounts for better table viewing.

Changes needed after Part 2 testing

---

contracts/fio.token/include/fio.token/fio.token.hpp

Dev Testing performed:
manual testing was performed on grants with 70M 7M 700k 70k to ensure that unlocking was accurate for the second grant period.
manual testing was performed to demonstrate the correction of the accounting for mis-accounted accounts:
Testing was performed by starting with the 2.2.x contracts with the unlock period shortened. One grant of type 1 was created for 70007834 FIO. The first unlock period was allowed to pass, then voting was performed (the unlock amount was correct), the second unlocking period was allowed to pass and then voting performed again (this time the unlock amount was much smaller than expected), this branches token and system contract were then built and set contract was used to set the token and then the system contract, then voting was performed, …

Fix bug in second unlocking period.

---

contracts/fio.token/include/fio.token/fio.token.hpp

fix error when users with mis-accounted period 2 genesis locked tokens try to correct the accounting using tranfer fio pub key.
obey the do update flag properly

fix bug when users try to fix period 2 genesis locks using transfer fio pub key

---

contracts/fio.token/include/fio.token/fio.token.hpp

this was tested with a 100M fio grant...
first the issue was illustrated (the result was a mis-accounted remaining locked token amount).
Then the fix was applied, and the result is now properly accounted locked token grants.

fix overflow issue when unlocking

---

contracts/fio.address/fio.address.cpp

There was an issue where a user was able to pass in 0 in their bundle count for addbundles.

BUG: Check for 0 addbundled assert

---

contracts/fio.address/fio.address.cpp

table reference had incorrect permissions which resulted in a bug in xferaddress and burnaddress

Update voters permission inside fio.address contract

---

contracts/fio.address/fio.address.cpp

In fio.address.cpp develop branch we were still using "add_bundled_transactions" instead of `ADD_BUNDLED_TRANSACTION_ENDPOINT`

Use ADD_BUNDLED_TRANSACTION_ENDPOINT on error

---

contracts/fio.request.obt/fio.request.obt.abi
contracts/fio.request.obt/fio.request.obt.cpp
contracts/fio.request.obt/fio.request.obt.hpp

This is the final version of the hotfix needed once the testnet has been reset to match the mainnet migration status.
**Table name change:**
fiotrxt -> fiotrxt_info
**Data member changes:**
init_time -> req_time
update_time -> obt_time
**New data member:**
req_content
obt_content
**Data member removed:**
content

Request and Obt index table hotfix ( with migration code fixes )

---

contracts/fio.address/fio.address.cpp
contracts/fio.request.obt/fio.request.obt.cpp

This PR gives the functionality of removing old data from the request and obt index tables. Block producers are able to call `migrtrx` and remove up to 25 records during a single transaction. Added functionality also allows for the API endpoints to use the new data structure introduced in step 1.

[FIP-1.b] Contracts Part 2: Remove old data from index table (FIO #185)(Old PR #9)

---

contracts/fio.request.obt/fio.request.obt.cpp

We noticed while migrating testnet timestamp data that it was possible to have large gaps of iteration index searches that had the possibility of timing out the transaction and taking longer than the approved transaction times.

Scope migration iteration into smaller sets for more optimized indexing. 

---

contracts/fio.staking/fio.staking.abi
contracts/fio.staking/fio.staking.cpp
contracts/fio.staking/fio.staking.hpp
contracts/fio.system/include/fio.system/fio.system.hpp
contracts/fio.token/src/fio.token.cpp

resolve 2755, logic errors when payouts is 0 and general lock periods are removed
because they are in the past during lock adaptation at unstaking, logic error when a period is not yet paid/unlocked but the lock period is in the past during lock adaptation at unstake. 
add a release date to ROE calculation before which the ROE will remain 1.
reduce the max number of general lock periods to become 50 for trnsloctoks
this was tested by changing the ROE to be in the past,
then running the stake-rewards-dev-tests.js to verify ROE is computed
then mod the release date to be in teh future,
rerun the tests and see ROE remains 1 and Rewards are not given as a result.
clean up ABI and init global state vars to 0
this was dev tested using several of the staking tests available in fio.test.
fio.test …

FIP-21 staking -- resolve BD-2755, also set release date for ROE computation, clean up ABI and set init of global state vars to 0

---

contracts/fio.common/fio.common.hpp
contracts/fio.staking/fio.staking.abi
contracts/fio.staking/fio.staking.cpp
contracts/fio.staking/fio.staking.hpp

lock adaptation needs to consider that a period might be paid out, and when this is the case DO NOT use this period as the insert period. Add an activation flag for staking rewards computation, once the threshold is crossed then rewards are activated in the protocol and always computed thereafter.
modify ram bump on stake and unstake to become 256.

FIP-21  add activated flag staking rewards,  handle edge condition in lock adaptation, reduce stake unstake RAM bump

---

contracts/fio.staking/fio.staking.cpp

if a precision issue results in srps to claim being less than the amount of the unstake, make this to no longer be a fatal error, instead it is a no rewards situation, so set the rewards to 0

FIP-21  Staking fix bug in computation of reward amount

---

contracts/fio.staking/fio.staking.cpp

rework the rate of exchange calculations 
use long double data type to protect against overflow while maintaining accuracy of resulting roe.
rename variables to add clarity.

FIP-21 Staking rework rate of exchange calculations.

---

contracts/fio.staking/fio.staking.cpp
contracts/fio.staking/fio.staking.hpp

update the combined token pool only with the amount minted, this makes the logic correct.

FIP-21 Staking update logic for incrementing combined token pool after minting staking rewards

---

contracts/fio.address/fio.address.cpp

-addnft decrement bundle by 2
-addnft, remnft, remallnft fee type check for endpoints changed to 1
-remnft provides "NFT not currently mapped" error if one encountered in the list does not exist instead of passing over it

FIP-27 fixes

---

contracts/fio.system/include/fio.system/fio.system.hpp
contracts/fio.system/src/fio.system.cpp

add a new system action to set an account unlimited.
when a new contract is created on chain, the account that is created gets created with limited RAM. This is different than when accounts are created at chain genesis, at genesis accounts are created with unlimited RAM (because they are created by the bios node during startup). So to compensate for this limitation of account creation the FIO protocol must add an action that will set a new account to be unlimited, this permits new contracts to be added to the FIO protocol without any changes to the FIO Core code.

FIP-21 Staking -- add a new system action to set an account unlimited

---

contracts/fio.common/fio.common.hpp
contracts/fio.staking/fio.staking.cpp

set ram bumps to become 512 for stake and unstake

FIP-21 Staking --update ram bump for staking to become 512, set enable to nov22 2021 0800 MST

---

contracts/fio.staking/fio.staking.cpp

fio addresses no longer expire, remove all checks for expired addresses.
special note -- both stake_fio and unstake_fio must be fully regression tested as a result of these changes....

FIP-21  Staking -- remove expired address exceptions

---

contracts/fio.staking/fio.staking.cpp
contracts/fio.token/include/fio.token/fio.token.hpp
contracts/fio.token/src/fio.token.cpp

fix ability to use locked tokens for fees.

FIP-21 Staking -- BD-3164 update to properly process fees when an account has only locked tokens

---

contracts/fio.escrow/fio.escrow.hpp

This will prevent a table migration in the future when searching for owners in the mrkplconfig table.

Add owner lookup to allow for multiple escrow marketplaces

---

contracts/fio.common/fio.common.hpp
contracts/fio.system/include/fio.system/fio.system.hpp
contracts/fio.system/src/fio.system.cpp
contracts/fio.token/include/fio.token/fio.token.hpp
contracts/fio.token/src/fio.token.cpp

make general locks to be able to be sent to pre existing accounts, if the account has general locks merge the locks, remove locks from accounts when all periods are in the past.

FIP-41 development iteration

---

contracts/fio.system/src/voting.cpp

add logic to clear the is_auto_proxy when voting occurs.
SPECIAL NOTE -- these changes need tested with all voting weight tests, auto proxy tests, and complete regressions as they impact many FIO operations by impacting the update_votes logic which is used on many (if not all) actions in the FIO protocol.

 BD-3835 Operational bug fix

---

contracts/fio.request.obt/fio.request.obt.abi

These two structs are used in the `newfundsreq` and the `recordobt` transactions, but are serialized and encrypted before being placed into the content. Because the content of these transactions is just a string, these structs don't exist in the ABI.
Adding the structs to the ABI empowers developers to use the ABI of the contract to know how to interact with the contract, instead of needing to go to some external source for documentation.

Added new_funds_content and record_obt_data_content to reqobt contract ABI

---

contracts/fio.staking/fio.staking.cpp
contracts/fio.token/include/fio.token/fio.token.hpp

add logic to check when fee cannot be covered during unstaking. protect against unexpected math in operations.

BD_3854.   handle when unstaking and not enough funds for fee.

---

contracts/fio.address/fio.address.cpp

This is a followup bugfix to https://github.com/fioprotocol/fio.contracts/pull/261

fix remnft iterate for no tokenid

---

contracts/fio.system/src/voting.cpp

regprod should not validate account mapping per spec causing errors

Remove BD-3073 from voting.cpp

---

contracts/fio.staking/fio.staking.cpp
contracts/fio.system/src/fio.system.cpp

these changes enforce that no duplicate entries in the locktokensv2 table can be created by addgenlocks. also the unsticking logic is enhanced to provide coverage for all cases of lock adaptation when users unstake.

BD-4082 Enhance locks to enforce no duplicate accounts, and handle all lock adaptation cases for unsticking

---

contracts/fio.system/src/fio.system.cpp

BD-4208 integrate BD-4162 changes into fio.contracts release 2.8.x

BD-4208 integrate BD-4162 changes into fio.contracts release 2.8.x

---

contracts/fio.address/fio.address.abi
contracts/fio.address/fio.address.cpp
contracts/fio.common/fio.common.hpp
contracts/fio.common/fiotime.hpp

First cut at regdomadd action for testing
Registers FIO Domain and Handle together under one action.
FIP-42 - https://github.com/fioprotocol/fips/blob/master/fip-0042.md

[FIP-42] Add regdomadd action

---

contracts/fio.address/fio.address.abi
contracts/fio.address/fio.address.cpp
contracts/fio.address/fio.address.hpp
contracts/fio.common/fio.common.hpp
contracts/fio.system/include/fio.system/fio.system.hpp
contracts/fio.system/include/fio.system/native.hpp
contracts/fio.system/src/fio.system.cpp
contracts/fio.token/include/fio.token/fio.token.hpp
contracts/fio.treasury/fio.treasury.cpp

FIPs36-40 clean PR

---

contracts/fio.address/fio.address.cpp

BD-4492 revise iterator processing

BD-4492 revise iterator processing

---

contracts/fio.request.obt/fio.request.obt.cpp

FIP-39 BD-4535 user proper encrypt key in new fio requests.

FIP-39 BD-4535 use proper encrypt key in new fio requests

---

contracts/fio.address/fio.address.cpp

FIP-39 BD-4537 update errors to match spec.

FIP-39 BD-4537 update errors to match spec

---

contracts/fio.address/fio.address.cpp

FIP-40 BD-4538 require auth of actor on cals to updcryptkey.

FIP-39 BD-4538 require auth of actor on calls to updcryptkey

---

contracts/fio.request.obt/fio.request.obt.cpp

bugfix use the correct account when verifying the request for obt data

bugfix-- use the correct payer account when verifying a request for obt.

---

contracts/fio.address/fio.address.abi
contracts/fio.address/fio.address.cpp

this is for the wrapping of fio domains, this will permit oracles to know when a domain is burned and take appropriate actions to burn the associated wrapped domain.

BD-4580 add action to transaction log for burn of domains

---

README.md
docs/releases-testnet.md
docs/releases.md

Update of Readme to include build instructions and general info comparable to fio readme. Also moved fio.mainnet release documentation to docs dir.

BD-4624 readme and release doc updates

---

contracts/fio.system/src/fio.system.cpp

get votable balance instead of spendable
testing:
test this by making proxy accounts that have staked tokens, proxy participant accounts with staked tokens, proxy accounts with locked tokens, proxy participant accounts with locked tokens.

BD-4669 audit vote get votable balance instead of spendable balance
